/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao_controle;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.ProdutoServico;
import modelo.dao.ProdutoServicoDAO;

/**
 *
 * @author karollyne
 */
public class CadastroProdutoServico extends javax.swing.JDialog {

    ProdutoServicoDAO psd = new ProdutoServicoDAO();
    private ProdutoServico psEdicao;

    /**
     * Creates new form Cadastro
     */
    public CadastroProdutoServico() {
        setModal(true);
        initComponents();
        this.psEdicao = new ProdutoServico();
    }

    public void setpsEdicao(ProdutoServico psEdicao) {
        this.psEdicao = psEdicao;
        setDados();
    }

    private boolean preecheuOsCampos() {
        if (jtfNome.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "O campo nome não pode ser vazio", "Atenção",
                    JOptionPane.WARNING_MESSAGE);
            jtfNome.requestFocus();
            return false;
        } else if (jtfValor.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "O campo valor não pode ser vazio", "Atenção",
                    JOptionPane.WARNING_MESSAGE);
            jtfNome.requestFocus();
        }
        return true;
    }

    private void getDados() {
        psEdicao.setNome(jtfNome.getText());
        psEdicao.setValor(Float.parseFloat(jtfValor.getText().replaceAll(",", ".")));

        if (jtfFrequencia.getText().equals("")) {
            psEdicao.setFrequenciaAplicacao(Integer.parseInt(jtfFrequencia.getText().replaceAll("", "0")));
        } else {
            psEdicao.setFrequenciaAplicacao(Integer.parseInt(jtfFrequencia.getText()));
        }
        if (jrbServico.isSelected()) {
            psEdicao.setServico(true);
        } else {
            psEdicao.setServico(false);
        }
    }

    private void setDados() {
        jtfNome.setText(psEdicao.getNome());
        jtfValor.setText(String.valueOf(psEdicao.getValor()));
        jtfFrequencia.setText(String.valueOf(psEdicao.getFrequenciaAplicacao()));

        if (psEdicao.isServico() == true) {
            jrbServico.doClick();
        } else {
            jrbProduto.doClick();
        }
        jlAlteraTexto.setText("Alterar dados de");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jlTitulo = new javax.swing.JLabel();
        jrbProduto = new javax.swing.JRadioButton();
        jrbServico = new javax.swing.JRadioButton();
        jtfNome = new javax.swing.JTextField();
        jtfValor = new javax.swing.JTextField();
        jtfFrequencia = new javax.swing.JTextField();
        jbSalvar = new javax.swing.JButton();
        jlAlteraTexto = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 500));

        jlTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jlTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlTitulo.setForeground(new java.awt.Color(1, 22, 59));
        jlTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTitulo.setText("Produtos e Serviços");

        jrbProduto.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jrbProduto);
        jrbProduto.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jrbProduto.setForeground(new java.awt.Color(1, 22, 59));
        jrbProduto.setSelected(true);
        jrbProduto.setText("Produto");
        jrbProduto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jrbServico.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jrbServico);
        jrbServico.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jrbServico.setForeground(new java.awt.Color(1, 22, 59));
        jrbServico.setText("Serviço");
        jrbServico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jtfNome.setBackground(new java.awt.Color(1, 22, 59));
        jtfNome.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jtfNome.setForeground(new java.awt.Color(255, 255, 255));
        jtfNome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 22, 59), 4));
        jtfNome.setPreferredSize(new java.awt.Dimension(280, 32));
        jtfNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfNomeKeyTyped(evt);
            }
        });

        jtfValor.setBackground(new java.awt.Color(1, 22, 59));
        jtfValor.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jtfValor.setForeground(new java.awt.Color(255, 255, 255));
        jtfValor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfValor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 22, 59), 4));
        jtfValor.setPreferredSize(new java.awt.Dimension(280, 32));
        jtfValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfValorKeyTyped(evt);
            }
        });

        jtfFrequencia.setBackground(new java.awt.Color(1, 22, 59));
        jtfFrequencia.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jtfFrequencia.setForeground(new java.awt.Color(255, 255, 255));
        jtfFrequencia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfFrequencia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 22, 59), 4));
        jtfFrequencia.setPreferredSize(new java.awt.Dimension(280, 32));
        jtfFrequencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfFrequenciaKeyTyped(evt);
            }
        });

        jbSalvar.setBackground(new java.awt.Color(1, 22, 59));
        jbSalvar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbSalvar.setForeground(new java.awt.Color(255, 255, 255));
        jbSalvar.setText("SALVAR");
        jbSalvar.setBorderPainted(false);
        jbSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbSalvar.setPreferredSize(new java.awt.Dimension(125, 32));
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jlAlteraTexto.setBackground(new java.awt.Color(255, 255, 255));
        jlAlteraTexto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlAlteraTexto.setForeground(new java.awt.Color(1, 22, 59));
        jlAlteraTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlAlteraTexto.setText("Cadastro de ");

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(1, 22, 59));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Nome");
        jTextField1.setBorder(null);
        jTextField1.setPreferredSize(new java.awt.Dimension(49, 32));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(1, 22, 59));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("Valor");
        jTextField2.setBorder(null);
        jTextField2.setPreferredSize(new java.awt.Dimension(49, 32));

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(255, 255, 255));
        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(1, 22, 59));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("Frequência de aplicação em dias");
        jTextField3.setBorder(null);
        jTextField3.setPreferredSize(new java.awt.Dimension(49, 32));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jlAlteraTexto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlTitulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jrbProduto)
                                .addGap(114, 114, 114)))
                        .addComponent(jrbServico))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfFrequencia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfValor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(209, 209, 209))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(jbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlAlteraTexto)
                    .addComponent(jlTitulo))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbProduto)
                    .addComponent(jrbServico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfValor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfFrequencia, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        if (preecheuOsCampos()) {
            try {
                getDados();
                psd.salvar(psEdicao);
                JOptionPane.showMessageDialog(this, "Salvo com sucesso!", "Sucesso",
                        JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
            } catch (Exception ex) {
                Logger.getLogger(ProdutoServicoDAO.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Preencha todos os campos corretamente", "Erro",
                        JOptionPane.ERROR_MESSAGE);

            }
        }
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jtfFrequenciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfFrequenciaKeyTyped

        if (!String.valueOf(evt.getKeyChar()).matches("[0-9]")) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfFrequenciaKeyTyped

    private void jtfValorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfValorKeyTyped
        if (!String.valueOf(evt.getKeyChar()).matches("[0-9 ,]")) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfValorKeyTyped

    private void jtfNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNomeKeyTyped
        //jtfNome.setForeground(Color.getHSBColor(150, 5, 17));
        if (!String.valueOf(evt.getKeyChar()).matches("[0-9, A-Z, a-z, ç, ã]")) {

            evt.consume();
        }
        if (String.valueOf(evt.getKeyChar()).matches(",")) {

            evt.consume();
        }

    }//GEN-LAST:event_jtfNomeKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutoServico.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutoServico.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutoServico.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutoServico.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProdutoServico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JLabel jlAlteraTexto;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JRadioButton jrbProduto;
    private javax.swing.JRadioButton jrbServico;
    private javax.swing.JTextField jtfFrequencia;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfValor;
    // End of variables declaration//GEN-END:variables
}
