/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao_controle;

/**
 *
 * @author karol
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jbCadastroClienteAnimal = new javax.swing.JButton();
        jbCadastroProdutoServico = new javax.swing.JButton();
        jbCadastroVenda = new javax.swing.JButton();
        jbPesquisaVenda = new javax.swing.JButton();
        jbPesquisaClienteAnimal = new javax.swing.JButton();
        jbPesquisaProdutoServico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(1);
        setResizable(false);

        jLayeredPane1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(1, 22, 59));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 325));

        jLabel1.setBackground(new java.awt.Color(255, 255, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(171, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
        );

        jbCadastroClienteAnimal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbCadastroClienteAnimal.setForeground(new java.awt.Color(255, 255, 255));
        jbCadastroClienteAnimal.setText("• Cadastrar Clientes e Animais");
        jbCadastroClienteAnimal.setBorderPainted(false);
        jbCadastroClienteAnimal.setContentAreaFilled(false);
        jbCadastroClienteAnimal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbCadastroClienteAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastroClienteAnimalActionPerformed(evt);
            }
        });

        jbCadastroProdutoServico.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbCadastroProdutoServico.setForeground(new java.awt.Color(255, 255, 255));
        jbCadastroProdutoServico.setText("• Cadastrar Produtos e Serviços");
        jbCadastroProdutoServico.setBorderPainted(false);
        jbCadastroProdutoServico.setContentAreaFilled(false);
        jbCadastroProdutoServico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbCadastroProdutoServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastroProdutoServicoActionPerformed(evt);
            }
        });

        jbCadastroVenda.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbCadastroVenda.setForeground(new java.awt.Color(255, 255, 255));
        jbCadastroVenda.setText("• Fazer uma venda");
        jbCadastroVenda.setBorderPainted(false);
        jbCadastroVenda.setContentAreaFilled(false);
        jbCadastroVenda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbCadastroVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastroVendaActionPerformed(evt);
            }
        });

        jbPesquisaVenda.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbPesquisaVenda.setForeground(new java.awt.Color(255, 255, 255));
        jbPesquisaVenda.setText("• Pesquisar Vendas");
        jbPesquisaVenda.setBorderPainted(false);
        jbPesquisaVenda.setContentAreaFilled(false);
        jbPesquisaVenda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbPesquisaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisaVendaActionPerformed(evt);
            }
        });

        jbPesquisaClienteAnimal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbPesquisaClienteAnimal.setForeground(new java.awt.Color(255, 255, 255));
        jbPesquisaClienteAnimal.setText("• Pesquisar Clientes e Animais");
        jbPesquisaClienteAnimal.setBorderPainted(false);
        jbPesquisaClienteAnimal.setContentAreaFilled(false);
        jbPesquisaClienteAnimal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbPesquisaClienteAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisaClienteAnimalActionPerformed(evt);
            }
        });

        jbPesquisaProdutoServico.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbPesquisaProdutoServico.setForeground(new java.awt.Color(255, 255, 255));
        jbPesquisaProdutoServico.setText("• Pesquisar Produtos e Serviços");
        jbPesquisaProdutoServico.setBorderPainted(false);
        jbPesquisaProdutoServico.setContentAreaFilled(false);
        jbPesquisaProdutoServico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbPesquisaProdutoServico.setPreferredSize(new java.awt.Dimension(275, 33));
        jbPesquisaProdutoServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisaProdutoServicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jbPesquisaClienteAnimal)
                                .addGap(14, 14, 14))
                            .addComponent(jbCadastroProdutoServico, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addComponent(jbCadastroClienteAnimal)
                        .addComponent(jbCadastroVenda)
                        .addComponent(jbPesquisaVenda))
                    .addComponent(jbPesquisaProdutoServico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jbCadastroClienteAnimal)
                .addGap(18, 18, 18)
                .addComponent(jbCadastroProdutoServico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbCadastroVenda)
                .addGap(18, 18, 18)
                .addComponent(jbPesquisaVenda)
                .addGap(18, 18, 18)
                .addComponent(jbPesquisaClienteAnimal)
                .addGap(18, 18, 18)
                .addComponent(jbPesquisaProdutoServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbCadastroClienteAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastroClienteAnimalActionPerformed
       new CadastroClienteAnimal().setVisible(true);
    }//GEN-LAST:event_jbCadastroClienteAnimalActionPerformed

    private void jbCadastroProdutoServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastroProdutoServicoActionPerformed
        new CadastroProdutoServico().setVisible(true);
    }//GEN-LAST:event_jbCadastroProdutoServicoActionPerformed

    private void jbPesquisaClienteAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisaClienteAnimalActionPerformed
        new PesquisaClientes().setVisible(true);
    }//GEN-LAST:event_jbPesquisaClienteAnimalActionPerformed

    private void jbPesquisaProdutoServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisaProdutoServicoActionPerformed
       new PesquisaProdutoServico().setVisible(true);
    }//GEN-LAST:event_jbPesquisaProdutoServicoActionPerformed

    private void jbCadastroVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastroVendaActionPerformed
        new CadastroVenda().setVisible(true);
    }//GEN-LAST:event_jbCadastroVendaActionPerformed

    private void jbPesquisaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisaVendaActionPerformed
       new PesquisaVenda().setVisible(true);
    }//GEN-LAST:event_jbPesquisaVendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbCadastroClienteAnimal;
    private javax.swing.JButton jbCadastroProdutoServico;
    private javax.swing.JButton jbCadastroVenda;
    private javax.swing.JButton jbPesquisaClienteAnimal;
    private javax.swing.JButton jbPesquisaProdutoServico;
    private javax.swing.JButton jbPesquisaVenda;
    // End of variables declaration//GEN-END:variables
}
